version: "3.7"
services:

  mongo:
    image: mongo
    restart: always
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: ${DB_LOGIN}
    # MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo-volume:/data/db

  zookeeper:
    image: zookeeper
    restart: "unless-stopped"
    tmpfs: "/datalog"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    # restart: "unless-stopped"
    restart: "always"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - "zookeeper"
    command:
      - "/bin/sh"
      - "-c"
      - 'echo "wait some time..." && /bin/sleep 10 && start-kafka.sh' # run kafka after sleep time for connect to zookeeper

volumes:
  mongo-volume:
    driver: local
